import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';

import {
  DxAccordionModule,
  DxButtonModule,
  DxChartModule,
  DxCheckBoxModule,
  DxDataGridModule,
  DxDropDownBoxModule,
  DxFileUploaderModule,
  DxFormModule,
  DxListModule,
  DxLoadIndicatorModule,
  DxLoadPanelModule,
  DxMenuModule,
  DxPieChartModule,
  DxPivotGridFieldChooserModule,
  DxPivotGridModule,
  DxPopoverModule,
  DxPopupModule,
  DxRadioGroupModule,
  DxSelectBoxModule,
  DxTagBoxModule,
  DxTemplateModule,
  DxTextBoxModule,
  DxTreeViewModule
} from 'devextreme-angular';

@NgModule({
  imports: [
    CommonModule,
    DxAccordionModule,
    DxButtonModule,
    DxChartModule,
    DxCheckBoxModule,
    DxDataGridModule,
    DxDropDownBoxModule,
    DxFileUploaderModule,
    DxFormModule,
    DxListModule,
    DxLoadIndicatorModule,
    DxLoadPanelModule,
    DxMenuModule,
    DxPieChartModule,
    DxPivotGridFieldChooserModule,
    DxPivotGridModule,
    DxPopoverModule,
    DxPopupModule,
    DxRadioGroupModule,
    DxSelectBoxModule,
    DxTagBoxModule,
    DxTemplateModule,
    DxTextBoxModule,
    DxTreeViewModule
  ],
  declarations: [],
  exports: [
    DxAccordionModule,
    DxButtonModule,
    DxChartModule,
    DxCheckBoxModule,
    DxDataGridModule,
    DxDropDownBoxModule,
    DxFileUploaderModule,
    DxFormModule,
    DxListModule,
    DxLoadIndicatorModule,
    DxLoadPanelModule,
    DxMenuModule,
    DxPieChartModule,
    DxPivotGridFieldChooserModule,
    DxPivotGridModule,
    DxPopoverModule,
    DxPopupModule,
    DxRadioGroupModule,
    DxSelectBoxModule,
    DxTagBoxModule,
    DxTemplateModule,
    DxTextBoxModule,
    DxTreeViewModule
  ]
})
export class DevExtremeModule {
}
